# Form implementation generated from reading ui file 'src/pyqt/ui/app.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(581, 258)
        MainWindow.setMinimumSize(QtCore.QSize(581, 258))
        MainWindow.setMaximumSize(QtCore.QSize(581, 258))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/Singula/Downloads/youtube.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: rgb(93, 224, 224);\n"
"}\n"
"\n"
"QWidget {\n"
"    font: 8pt \"JetBrains Mono\";    \n"
"    background-color: rgb(81, 86, 109);\n"
"    color: rgb(219, 225, 255);\n"
"}\n"
"\n"
"#infiInner {\n"
"    width: 100px;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QComboBox {\n"
"    border: 2px solid rgb(93, 224, 224);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    font-size: 14px;\n"
"    border: 2px solid rgb(93, 224, 224);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#videoInfo {\n"
"    font-size: 14px;\n"
"    border: 2px solid rgb(93, 224, 224);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#config {\n"
"    font-size: 14px;\n"
"    border: 2px solid rgb(93, 224, 224);\n"
"    border-radius: 10px;    \n"
"}\n"
"\n"
"#videoUrl {\n"
"    font-size: 15px;\n"
"    border: 2px solid rgb(93, 224, 224);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#configBtn_2 {\n"
"    font-size: 15px;\n"
"    border: 2px solid rgb(93, 224, 224);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#configBtn_3 {\n"
"    font-size: 15px;\n"
"    border: 2px solid rgb(93, 224, 224);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#configBtn_4 {\n"
"    font-size: 15px;\n"
"    border: 2px solid rgb(93, 224, 224);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#progressBar {\n"
"    text-align: center;\n"
"    font-size: 15px;\n"
"    width: 100%;\n"
"    border: 2px solid rgb(93, 224, 224);\n"
"    border-radius: 10px;\n"
"}\n"
"")
        MainWindow.setIconSize(QtCore.QSize(30, 30))
        MainWindow.setAnimated(True)
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.videoUrl = QtWidgets.QLineEdit(self.centralwidget)
        self.videoUrl.setGeometry(QtCore.QRect(60, 10, 441, 31))
        self.videoUrl.setStyleSheet("")
        self.videoUrl.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.videoUrl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.videoUrl.setClearButtonEnabled(False)
        self.videoUrl.setObjectName("videoUrl")
        self.videoInfo = QtWidgets.QGroupBox(self.centralwidget)
        self.videoInfo.setGeometry(QtCore.QRect(20, 50, 181, 131))
        self.videoInfo.setObjectName("videoInfo")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.videoInfo)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 161, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.infiInner = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.infiInner.setContentsMargins(0, 0, 0, 0)
        self.infiInner.setObjectName("infiInner")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.infiInner.addWidget(self.lineEdit_4)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setMaxLength(17)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.infiInner.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setMaxLength(17)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.infiInner.addWidget(self.lineEdit_3)
        self.config = QtWidgets.QGroupBox(self.centralwidget)
        self.config.setGeometry(QtCore.QRect(400, 50, 161, 131))
        self.config.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.config.setObjectName("config")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.config)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 121, 101))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.configBtn_4 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.configBtn_4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.configBtn_4.setObjectName("configBtn_4")
        self.verticalLayout.addWidget(self.configBtn_4)
        self.configBtn_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.configBtn_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.configBtn_2.setCheckable(False)
        self.configBtn_2.setDefault(False)
        self.configBtn_2.setObjectName("configBtn_2")
        self.verticalLayout.addWidget(self.configBtn_2)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(60, 210, 441, 31))
        self.progressBar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.WaitCursor))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 60, 158, 21))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(220, 90, 158, 20))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YoutubeDownloader"))
        self.videoUrl.setPlaceholderText(_translate("MainWindow", "VIDEO URL"))
        self.videoInfo.setTitle(_translate("MainWindow", "Video Info"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Duration"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Video name"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Author"))
        self.config.setTitle(_translate("MainWindow", "Config"))
        self.configBtn_4.setText(_translate("MainWindow", "Download"))
        self.configBtn_2.setText(_translate("MainWindow", "Get info"))
        self.label.setText(_translate("MainWindow", "Quality"))

